# Configuration file for the Sphinx documentation builder.
# Generated by pharaoh-bootstrap

project = "RemotiveLabs Topology + Sphinx-Needs traceability"
copyright = "2026, RemotiveLabs & useblocks Partnership"
author = "RemotiveLabs / useblocks"
release = "0.1.0"

extensions = [
    "sphinx_needs",
    "sphinxcontrib.mermaid",
    "sphinxcontrib.plantuml",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

html_theme = "furo"
html_static_path = ["_static"]
html_css_files = ["_css/useblocks.css"]

html_theme_options = {
    "sidebar_hide_name": True,
    "light_logo": "useblocks-logo-light.svg",
    "dark_logo": "useblocks-logo-dark.svg",
}

# sphinx-needs reads all type/link/field config from ubproject.toml
needs_from_toml = "ubproject.toml"
