services:
  udptools:
    hostname: udptools
    tty: true
    image: remotivelabs/remotivelabs-python-runner:sha-63191bb
    networks:
      - docker_local
    ports:
      - "2000:2000/udp"
    volumes:
      - ./udptools:/work
    working_dir: /work
    environment:
      - SERVER_PORT=2000
    command: python3 logger.py

networks:
  docker_local:
    driver: bridge
