services:
  web-client:
    stdin_open: true
    tty: true
    image: remotivelabs/remotive-web-app:${REMOTIVEWEBAPP_TAG:-latest}
    ports:
      - "8080:8080"

  remotive-broker:
    ports:
      - "50051:50051"
      - "8081:8081"
    tty: true
    image: remotivelabs/remotivebroker-server:${REMOTIVEBROKER_TAG:-v1.10.1}
    cap_add:
      - NET_ADMIN
    # Mount the folder "configuration" folder into container.
    # configurable through an environment variable (or set in a .env file).
    mac_address: 02:00:00:00:ab:12
    volumes:
      - "./configuration_udp:/signalbroker/_build/prod/rel/signal_server/configuration"
    # Use this if you need to customize the command that this container runs;
    # set the variable in a .env file.
    # command: "${CUSTOM_COMMAND}"
    environment:
      - REPLACE_OS_VARS=true
      - COOKIE=test
      - NODENAME=node@${NODE_NAME:-unset.example.com}
    env_file:
      - ../REMOTIVEBROKER_LICENSE
    networks:
      - docker_local
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:50051"]
      interval: 1s
      timeout: 10s
      retries: 10

networks:
  docker_local:
    driver: bridge
