schema: remotive-topology-instance:0.12

containers:
  android_emulator:
    build:
      dockerfile: ../containers/android_emulator/Dockerfile
    working_dir: /app
    ports:
      - "8085:8080"
    devices:
      - /dev/kvm
    environment:
      - ANDROID_EMULATOR_AUTH=${ANDROID_EMULATOR_AUTH:-}

ecus:
  IHU:
    models:
      ihu:
        type: container
        container:
          build:
            context: ../
            dockerfile: ../ecus/ihu/Dockerfile.ihu
          volumes:
            - ../ecus/ihu:/app/ihu
          working_dir: /app
          command: python -m ihu
          environment:
            - ANDROID_EMULATOR_AUTH=${ANDROID_EMULATOR_AUTH:-}
            - ANDROID_ADB_SERVER_ADDRESS=android_emulator
            - ANDROID_EMULATOR_ADDRESS=android_emulator
            - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
