@startuml
robust "Value on CAN bus" as CAN
robust "Value in simulation" as SIM
scale 1000 as 130 pixels

@CAN
0 is "Init"

@SIM
0 is "Init"

@SIM
900 is "Update 1"
@900 <-> @1000 : Update 1 window

@CAN
1000 is "Update 1"


@SIM
+900 is "Update 2"
@1900 <-> @2000 : Update 2 window

@CAN
+100 is "Update 2"

@SIM
+900 is "Update 3"
@2900 <-> @3000 : Update 3 window

@CAN
+100 is "Update 3"

@enduml
