FROM python:3.13-slim

COPY pyproject.toml README.md LICENSE .
COPY ecus/ ./ecus/
RUN pip install .

RUN jupyter labextension enable --py widgetsnbextension
CMD ["jupyter-lab", "--allow-root", "--ip", "0.0.0.0", "--port", "8888", "--NotebookApp.token=remotivelabs", "--no-browser", "--FileCheckpoints.checkpoint_dir=/tmp"]
