- hosts: remote
  become: true
  gather_facts: true

  pre_tasks:
    - name: Update APT cache and install dependencies
      apt:
        name: "{{ apt_packages }}"
        state: present
        update_cache: true

    - name: Check if docker command exists
      ansible.builtin.command: which docker
      register: docker_check
      ignore_errors: true

  roles:
    - role: docker
      # Do not touch docker installation if already installed. We cannot know the origin of docker
      when: docker_check.rc != 0

    - role: remotivebus

    - role: remotive_cli
